# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
inhibit_all_warnings!

target 'Push' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Push
  pod 'lottie-ios'
  pod 'Resolver'

  # Pods for Push - Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift'

  target 'PushTests' do
    inherit! :search_paths
    
    # Pods for testing
    pod 'Nimble'
  end

  target 'PushUITests' do
    # Pods for testing
  end
end
