# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
inhibit_all_warnings!

target 'Push' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Push
  pod 'lottie-ios'
  pod 'Resolver'

  # Pods for Push - Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift'

  target 'PushTests' do
    inherit! :search_paths
    
    # Pods for testing
    pod 'Nimble'
  end

  target 'PushUITests' do
    # Pods for testing
  end
end

post_install do |installer|
  # Removes the warning about swift conversion.
  installer.pods_project.root_object.attributes['LastSwiftMigration'] = 9999
  installer.pods_project.root_object.attributes['LastSwiftUpdateCheck'] = 9999
  installer.pods_project.root_object.attributes['LastUpgradeCheck'] = 9999
  
  # Removes the warning about deployment target.
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
